### ISSUE TITLE
Add docs/demo on using new custom element

### ISSUE THREAD

**Issue by hotforfeature** [hotforfeature/origami#16]
It's not obviously clear on how to create your own Polymer element within an Angular app. An example in the demo repository will help.

**Comment by rainstormza** [comment]
+1

**Comment by warri93** [comment]
Does someone know how to do this? Adding a custom polymer component?

**Comment by hotforfeature** [comment]
Yup! It's quite easy actually. The gist of it is you want to add the polymer component to your `assets` folder and import it like you would any other element. 

The important thing is that the actual HTML is included in the project build. You have to create the file somewhere Angular knows to import it. It can't be within an Angular template.

So it's easy, but not very apparent where you need to create/import the element. I'll try and put together a sample in the demo folder soon.

**Comment by hotforfeature** [comment]
I've added a sample custom element to the demo app, but I still think this would benefit from a full docs page on it. I'll get to that later.

**Comment by rainstormza** [comment]
I've tried your demo.

npm install
ng serve

but it doesn't work and error happens a lot :(

do you have any solution to use your demo file ?

thanks

**Comment by BorntraegerMarc** [comment]
@rainstormza what kind of error are you getting? For me it worked

**Comment by rainstormza** [comment]
![image](https://cloud.githubusercontent.com/assets/4003032/26146228/9c579e08-3b19-11e7-8c66-1986e168e2ee.png)

error like this

my step:
- download source from git
- npm install
- ng serve

Is there any step that I forgot ?

@BorntraegerMarc

**Comment by BorntraegerMarc** [comment]
@rainstormza did you run `npm install --save @codebakery/origami` in the project?

**Comment by rainstormza** [comment]
yes , I did @BorntraegerMarc

**Comment by BorntraegerMarc** [comment]
Ok and what source did you download from git?

**Comment by rainstormza** [comment]
https://github.com/hotforfeature/origami.git

this source

**Comment by hotforfeature** [comment]
@rainstormza the demo app uses a symlink to connect to the source code, which doesn't work on windows.

Do a global search and replace of `origami/origami` with `../../src/origami` in the demo folder, it'll start working then. This is the second time someone's had problems with it, I'll open an issue to remove the symlink.

**Comment by hotforfeature** [comment]
Actually looks like it's not as simple as replacing the relative url, since the src folder lives outside of the demo app, which has its own package.json and node_modules.

In Windows though, delete the `origami` file located at `demo/src/origami`. Create a new linked folder titled "origami" and point it to the `src` folder of the main repo. [This guide gives a quick overview](https://www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/) of making linked folders in Windows if you don't know how.

It'd be great if a format would make the symlink work both on Windows and Linux, I'll have to experiment. Otherwise, some other solution would be needed.

**Comment by BorntraegerMarc** [comment]
This problem is only for this specific demo, right

**Comment by hotforfeature** [comment]
That's correct, it's just due to how I organized the demo folder that is Linux-specific. You can remove the symlinks and replace them with `import { ... } from @codebakery/origami` to make it use the npm-installed version instead. Additionally this only happens on Windows.
