### ISSUE TITLE
Error when using copying demo

### ISSUE THREAD

**Issue by BorntraegerMarc** [hotforfeature/origami#22]
When I followed the quick start I got the error:
```
AppComponent.html:6 ERROR Error: If ngModel is used within a form tag, either the name attribute must be set or the form
      control must be defined as 'standalone' in ngModelOptions.

      Example 1: <input [(ngModel)]="person.firstName" name="first">
      Example 2: <input [(ngModel)]="person.firstName" [ngModelOptions]="{standalone: true}">
```

**Comment by BorntraegerMarc** [comment]
When adding the name tag to `<paper-input label="Name" required [(ngModel)]="name" name="name"></paper-input>` the error was resolved. Should I add this to the quick start docs? Or should we suggest the standalone option?

**Comment by hotforfeature** [comment]
This is a standard error when using NgModel incorrectly. I'm not sure this needs to be documented, it's required that NgModel has a name attribute when used in a form. You'll get the same error if you try to use an `<input [(ngModel)]="value">` without a name attribute.

**Comment by BorntraegerMarc** [comment]
But the demo does not include the `name` attribute. Should I include it? I guess it's mandatory...

**Comment by hotforfeature** [comment]
I don't see anywhere in the demo where I'm using a form, are you referring to https://github.com/hotforfeature/origami/blob/master/demo/src/app/app.component.html#L20?

When used outside of a form, `NgModel` does not require a name attribute. Inside a form, it does. The [Angular docs](https://angular.io/docs/ts/latest/guide/forms.html) describe this, though not very obviously, as part of the intro to forms.

**Comment by BorntraegerMarc** [comment]
Sorry, should have been more specific. Was referring to the README: https://github.com/hotforfeature/origami/blob/master/README.md

```
<form #ngForm="ngForm">
  <paper-input label="Name" required [(ngModel)]="name"></paper-input>

  <paper-button [disabled]="!ngForm.form.valid" (click)="onSubmit()">Submit</paper-button>
</form>
```

**Comment by hotforfeature** [comment]
Ah, yes that code sample is missing the name attribute. I'll fix it.
