### ISSUE TITLE
Research and create a demo for custom webpack builds

### ISSUE THREAD

**Issue by BorntraegerMarc** [hotforfeature/origami#25]
Currently we use a weird mix of polymer-build and angular webpack magic to get the production build working. Maybe an extension to the angular-cli build would be the answer...

I still trying to figure out how to use a hash when building the polymer parts. Basically what Angular does:
- build sources and create new file names as a hash. for example: `[hash].bundle.js`
- Reference that hash in the generated `index.html`
Now if the browser fetches `index.html` it will receive the notification that the cached version and the stored version is not byte identical and trigger an update. (because the new `[hash].bundle.js` got changed. This is a quite normal best practice when working with cache in web browsers

I wanted to apply the concept to the polymer build. So probably something like this https://github.com/sindresorhus/gulp-rev would need to be used. Basically:
- Specify the entrypoint is `elements.html`
- Generate `[hash].elements.html` with all the other imports hashed as well
- AND not comes the tricky part: Reference that `[hash].elements.html`in our `index.html`. Which is generated through Angular

Because angular theoretically does not "know" about the polymer build it is difficult to include the generated `[hash].elements.html` for the prod build. I already found some work around, which work OK. But if someone wants to really build a correctly cached + managed production web app, this would be a mandatory step...

OK, after some digging around I think we should include a example on how to use the origami demo project without the scaffolded project using `ng new projectname`. So basically include a demo on how to build an angular project by using pure webpack configs. Here some reasons:

- If we want to include a "real" custom build we can anyhow not use angular-cli, because we need to add configs like `SWPrecacheWebpackPlugin`. (side note: maybe use https://github.com/angular/mobile-toolkit/tree/master/service-worker/worker to bring it to work)
- We need to use plugins for certain edge cases. For example:
```
    plugins: [
        new webpack.LoaderOptionsPlugin({
            options: {
                htmlLoader: {
                    // First the tag name and then the attribute name
                    attrs: ['iron-image:src', 'iron-icon:src', 'paper-icon-button:src']
                }
            }
        })
    ]
```

**Comment by BorntraegerMarc** [comment]
OK @hotforfeature, so basically I found a way to to still use angular-cli and https://github.com/angular/mobile-toolkit to achieve a offline & push ready angular PWA app:

If we combine your production build option with mobile-toolkit then we get a "nearly-feasible" production build. The only thing that needs to be adapted is in the `ngsw-manifest.json` file the `static.ignore` property. Here it gets a bit hacky: Each and every file in `/assets/bower_components/**` needs to be listed here, that should get excluded. So basically 99% of all files.

Because unfortunately the angular build **needs** to run before the polymer build. So we have all unprocessed assets in the bower_components...

Do you want me to document all my finding (and solution) in a file? Or do you think it is not needed?

**Comment by hotforfeature** [comment]
Sounds promising! I'd welcome some starting documentation or a sample implementation that explains the basic steps.

**Comment by BorntraegerMarc** [comment]
https://medium.com/dev-channel/how-to-use-polymer-with-webpack-b41812d78b15

**Comment by hotforfeature** [comment]
Going to close this as we'll be getting production ready webpack stuff with all of the glorious hashing bells and whistles in v2 🙂
