### ISSUE TITLE
Add external stylesheet support

### ISSUE THREAD

**Issue by hotforfeature** [hotforfeature/origami#32]
This really [is a ShadyCSS problem](https://github.com/webcomponents/shadycss/issues/97), but we could add a service to automatically wrap `<link rel="stylesheet">`.

The service would need to wait for the links to load, then take their text content and apply them to a `<custom-style><style is="custom-style">...</style></custom-style>` element and replace the link with the generated content.

**Comment by asyncLiz** [comment]
Implemented in v3!
