### ISSUE TITLE
how to support vaadin-grid

### ISSUE THREAD

**Issue by keyeMyria** [hotforfeature/origami#34]
how to support vaadin-grid [vaadin-grid](https://github.com/vaadin/vaadin-grid)?

**Comment by hotforfeature** [comment]
The grid is not currently working and relies on https://github.com/vaadin/vaadin-grid/issues/890 for support. You can take a look at vaadin branch of this repo for a WIP implementation. I'm also tracking full vaadin element support in #18, so subscribe to that issue to be notified of support.

Aside from the grid, most all other vaadin elements that I've tested work perfectly.
