### ISSUE TITLE
Feature request: Expose polymer methods

### ISSUE THREAD

**Issue by BorntraegerMarc** [hotforfeature/origami#39]
So that we can call methods like `Polymer.dom()` directly from our TS code. Not sure though if it would make more sense for the polymer team to publish a typescript definition file...

**Comment by hotforfeature** [comment]
I'd join the #typescript channel on Polymer slack. I haven't kept a close eye on it, but some developers have already talked about typings for Polymer 2.

You could try [`@types/polymer-ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/polymer-ts/index.d.ts) which at a glance look like they fill in the gaps for Polymer 2.

You can declare `window.Polymer` as` <any>` and use the functions directly. Or [if you're like me and can't stand `<any>`](https://github.com/hotforfeature/origami/blob/master/src/util/Polymer.ts) you can extend the window interface or my Polymer interface and add the methods you're missing manually.

Though as I mentioned in the other issue, `Polymer.dom()` _shouldn't_ be used in Polymer 2 elements. It only serves as a bridge for a hybrid element that needs to support dom apis in both Polymer 2 and 1.

I don't think I'd want to support maintaining Polymer typings in this project. If `@types/polymer-ts` isn't good enough, I could see value in creating a new project to maintain typings on, but I'd want to do some talking with the #typescript channel first and see what the community has already done.
