### ISSUE TITLE
Can't get emitChanges to work

### ISSUE THREAD

**Issue by DaveMonag** [hotforfeature/origami#42]
I've got a Polymer component holding property "prop2" and an Angular component using the element and two way binding.

In angular:
```
<my-poly-element emitChanges [(prop2)]="myProperty"></my-poly-element>
<input type="text" [(ngModel)]="myProperty">
```

Inside the polymer component I have:

```
<link rel="import" href="../../bower_components/polymer/polymer-element.html">

<dom-module id="my-poly-element">

  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <button on-click="handleClick2">Click me to change value</button>
    <div>[[prop2]]</div>
  </template>

  <script>
    class PolymerAppTestElement extends Polymer.Element {
      static get is() { return 'my-poly-element'; }
      static get properties() {
        return {
          prop2: {
            type: String,
            value: 'Value to be changed'
          }
        };
      }
      handleClick2() {
        this.prop2 = "Changed!"
      }
    }

    customElements.define(PolymerAppTestElement.is, PolymerAppTestElement);
  </script>
</dom-module>

```

When I type in the textbox, it changes the value of prop2 in Polymer, but when clicking the button in the polymer component, the textbox does not change it's value to the same as the text field (it should be "Changed!"). 
Where myProperty is defined as:
`
  @PolymerChanges() myProperty: string;
`
I'm trying to use emitChanges to get the Polymer change detection to work with Angular change detection, but it doesn't look like the model is working. Any idea what I'm missing here? Sorry if this is an obvious/stupid question, but I couldn't figure it out from the docs.

**Comment by hotforfeature** [comment]
Your `prop2` needs to emit change events. You can do this by setting `notify: true` on the property declaration.

```js
      static get properties() {
        return {
          prop2: {
            type: String,
            value: 'Value to be changed',
            notify: true
          }
        };
      }
```

**Comment by DaveMonag** [comment]
Perfect, thanks!
