### ISSUE TITLE
data binding not working for dashed style properties

### ISSUE THREAD

**Issue by mandarsd** [hotforfeature/origami#44]
Data binding is not working for dashed style property names. Has anybody else noticed this issue?

**Comment by hotforfeature** [comment]
Can you give an example?

Remember that Angular binds to properties, not attributes. Properties are camelCase in Polymer, while their attribute reflection is dashed-case.

Polymer:
```html
<app-drawer-layout responsive-width="[[getWidth()]]">
```

Angular:
```html
<app-drawer-layout [responsiveWidth]="getWidth()">
<!-- or -->
<app-drawer-layout [attr.responsive-width]="getWidth()">
```

**Comment by mandarsd** [comment]
Sorry! My bad!
I was doing - `<app-drawer-layout [responsive-width]="getWidth()">`

Thank you very much for the detailed reply! 
Closing the issue :)
