### ISSUE TITLE
Can't bind to 'polymer' since it isn't a known property of 'template'

### ISSUE THREAD

**Issue by musti2** [hotforfeature/origami#48]
Hi Team,

I'm trying to use origami with vaadin-grid.git#column-template-observer and using the code from the origami vaadin-grid branch and I seem to encounter the following error:

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'polymer' since it isn't a known property of 'template'
```

and the code:
```
  <vaadin-grid emitChanges [items]="items | async" id="material" size="200">
    <vaadin-grid-selection-column width="66px" flex="0">
      <template [polymer]="this" class="header" ngNonBindable>
        <i on-click="contextMenuAlert">checkbox</i>
      </template>
      <template ngNonBindable>
        <paper-checkbox checked="{{selected}}"></paper-checkbox>
      </template>
    </vaadin-grid-selection-column>
```

My goal here is to trigger the on-click event for the <i> elem.. or any other element inside a Polymer <template>.

If i remove [polymer]="this" The component works, however, my event bindings no longer work.

origami version: 1.2.3

**Comment by hotforfeature** [comment]
It looks like this template is part of a module that hasn't imported `PolymerModule`. What does your app's module look like?

**Comment by musti2** [comment]
I've imported the PolymerModule into my app.module.ts:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { RouterModule, PreloadAllModules } from '@angular/router';
import { HttpModule } from '@angular/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { AppComponent } from './app.component';
import { routes } from './app-routing.module';


import { PolymerModule } from '@codebakery/origami';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    HttpModule,
    BrowserAnimationsModule,
    PolymerModule.forRoot(),
    RouterModule.forRoot(routes, { useHash: true, preloadingStrategy: PreloadAllModules })
  ],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
```

**Comment by musti2** [comment]
I found the issue.

I had to import PolymerModule into my child route module as well.

**Comment by musti2** [comment]
Just to be clear, i'm trying to trigger the click event of a native HTML element inside a `<template>` tag - and the function is defined in angular, not in the polymer component.

**Comment by hotforfeature** [comment]
For the module issue, I'm guessing there may be complications with lazy loading the child module. I myself use lazy loaded child modules, but they all import a shared module that imports and re-exports `PolymerModule`.

As far as the click handler, I copied the above template and replaced the `<vaadin-grid-selection-column>` in my vaadin branch demo app with it. The method is triggered and the alert fires. Can you post your entire component?

**Comment by hotforfeature** [comment]
@musti2 any update? Are you still having issues or can we close this issue?

**Comment by hotforfeature** [comment]
@musti2 I'm going to close this since there hasn't been an update. Feel free to comment if you're still having issues.
