### ISSUE TITLE
NG4 + P-2.0 does not work in IE

### ISSUE THREAD

**Issue by jayeshagwan1** [hotforfeature/origami#56]
My ng4+p2 app works fine in Chrome and FF, but does not load in IE. Tested in versions Edge, IE 9, IE 8 

![image](https://user-images.githubusercontent.com/616970/30163029-f2c2f9ac-93f4-11e7-859b-a029da301a01.png)

**Comment by BorntraegerMarc** [comment]
@jayeshagwan1 do you do a prod build and serve ES5? IE can't deal with "normal" components which uses ES6 classes...

**Comment by BorntraegerMarc** [comment]
Plus only IE 11 is supported...

**Comment by hotforfeature** [comment]
Polymer (and therefore Origami) only [support IE11 and Edge](https://github.com/hotforfeature/origami#browsers), so this behavior is expected.

For Edge and IE11, or any browser that does not have ES6 classes, the polymer assets must be transpiled to ES5. Unfortunately the Angular CLI does not do this as part of the dev server, so you won't be able to use `ng serve` for those browsers. Instead, you will need to [build Polymer](https://github.com/hotforfeature/origami/blob/master/docs/production-build.md#build-polymer) before testing in Edge or IE11.
