### ISSUE TITLE
Origami Demo application not working/loading correctly on IE

### ISSUE THREAD

**Issue by nishantgirbar** [hotforfeature/origami#63]
Hi,

I am trying to run demo origami application on IE but its not loading whereas in Google Chrome working fine. 

Object doesn't support property or method 'Call'
Object doesn't support property or method 'ElementMixin' and many more issues.

Could you please help me sort out this issue.

Thanks,
Nishant Kumar

**Comment by BorntraegerMarc** [comment]
@nishantgirbar did you compile with the `--prod` option? and are you serving the `es5` folder? IE can only support es5...

**Comment by nishantgirbar** [comment]
Thanks for your quick reply, but sorry how to serve with es5 folder ? I can see in polyfills.ts IE supports are un-commented for core-js/es5 and core js having es 5 folder as well.

Thanks,
Nishant Kumar

**Comment by BorntraegerMarc** [comment]
How did you start the web server? Or are you using the normal `ng serve --prod` option to look at it in IE?

**Comment by nishantgirbar** [comment]
yes exactly and its launching as http://localhost:4200

**Comment by hotforfeature** [comment]
With the current build process, Angular CLI's webpack is transpiling Angular code (and polyfills) down to ES5 on the fly, but it has no knowledge of the Polymer imports that are included via `<link>`s.

So `ng serve` will be serving mixed ES5/ES6 code, and IE11 doesn't support ES6. The only way to test IE11 (or other browsers that do not support ES6) is to fully build the project. I use [http-server](https://www.npmjs.com/package/http-server) to help me with this.

Run `npm run build`, then `cd build/es5-bundled/` and run `http-server`. That'll spin up a local server in the built directory. You can then test IE11 by going to `http://localhost:8080`.

The new build process I'm working on is a lot more forgiving and will allow `ng serve` to work in IE11.

**Comment by nishantgirbar** [comment]
thanks a lot its working fine with http server.

**Comment by hotforfeature** [comment]
Sounds good!
