### ISSUE TITLE
Application not working on IE when  trying to  ag grid in the application

### ISSUE THREAD

**Issue by nishantgirbar** [hotforfeature/origami#68]
Hi,

Application working file on IE as well as Chrome as well, but when trying to add ag grid in app.module as below code then application is not working at all on IE but working fine on Chrome.

import {AgGridModule} from "ag-grid-angular/main";

@NgModule({
  imports: [
    AppElementsModule,
    BrowserModule,
    CommonModule,
    FormsModule,
    HttpModule,
    IronElementsModule,
    PaperElementsModule,
    PolymerModule.forRoot(),
    AgGridModule.withComponents([])
  ],

app loading fine on Chrome but on IE with es5(build version) not working/loading.

Could you please help me sort out this issue.

Regards,
Nishant Kumar

**Comment by hotforfeature** [comment]
ag-grid-angular is an Angular library, not a Polymer element. What errors are you seeing that makes you think Polymer or Origami are causing conflict?

**Comment by nishantgirbar** [comment]
Can't see any error but as soon as giving just reference of ag grid angular in app module file its stopping loading of app on IE.

**Comment by nishantgirbar** [comment]
I have just seen below is the list errors in console I am getting on IE browser, even it is loading correctly:

SCRIPT5022: A custom element with name 'iron-meta' has already been defined
SCRIPT5022: A custom element with name 'dom-if' has already been defined.
File: webcomponents-lite.js, Line: 154, Column: 90

![image](https://user-images.githubusercontent.com/18031306/32032092-eaa2929c-ba22-11e7-9aab-2683c4cec171.png)

**Comment by nishantgirbar** [comment]
by continuing in above post, as soon as if we refer ag-grid in origami demo project getting above errors for element already defined.
Please help me to sort this issue.

**Comment by hotforfeature** [comment]
Can you branch the origami demo project and include ag-grid in it for me? I've seen these errors when elements are getting imported twice, so it may just be a build configuration issue.

I don't see anything in ag-grid yet that would cause this problem.

**Comment by nishantgirbar** [comment]
thanks for your message, here i am attaching zip file which having demo project by adding reference of ag-grid.
[Polymer2.zip](https://github.com/hotforfeature/origami/files/1419338/Polymer2.zip)

**Comment by hotforfeature** [comment]
I don't receive any errors in IE11, though I think I might know what the problem is. Are you trying to navigate to the app while it's being served via the Angular CLI in dev mode?

With Origami v1's build process, this is not possible since the Angular CLI will not transpile Polymer ES6 classes on the fly. You need to run `npm run build` and generate a built and bundled version, then serve the `build/es5/` directory using something like [http-server](https://www.npmjs.com/package/http-server).

After building, here's a screenshot of the app in IE11 with no console errors.
![screen shot 2017-10-26 at 2 43 47 pm](https://user-images.githubusercontent.com/14365924/32073655-656e1742-ba5c-11e7-91cd-b61b5589df11.png)

**Comment by nishantgirbar** [comment]
Sorry I sent wrong zip will send another one and yes I am doing the same process, and also could you please delete above screenshot post for me?

**Comment by nishantgirbar** [comment]
@hotforfeature : thanks  a lot for your review and debugging, but sorry the zip file which I sent you earlier was wrong one and by mistake I sent that one, please find correct zip file which is working in Chrome on http-server but on IE having issue.
[demo.zip](https://github.com/hotforfeature/origami/files/1420817/demo.zip)

**Comment by hotforfeature** [comment]
It looks like the problem may lie in how the Polymer CLI is transpiling JavaScript after it has been built. If you scroll up in your errors, you'll see some error in the vendor file that a property cannot be declared twice. This is coming from ag-grid somewhere.

I added `"js": { "minify": false }` to the `es5` section of `polymer.json`, and removed `--prod` from the npm build script to get it to work. I didn't have success re-adding `--prod`, but there may be a deeper error related to the demo repo causing that.

So in your project, I'd try just adding the minify false flag to your es5 build to see if that works. I've seen issues in the past where transpiling twice (once via Angular and again via Polymer) has had weird effects even though it hypothetically shouldn't.

**Comment by nishantgirbar** [comment]
Thanks a lot @hotforfeature  its working fine by following your steps.

**Comment by nishantgirbar** [comment]
@hotforfeature application loading correctly but ag-grid is not loading at all.

**Comment by hotforfeature** [comment]
@nishantgirbar have you tried setting up your project with ag-grid and **not** Polymer or Origami? There is nothing in this project that would prevent ag-grid from working. This sounds more and more like a build and/or compatibility issue.

**Comment by nishantgirbar** [comment]
@hotforfeature  yes if I have setup a project with ag-grid and polymer 1.0 which is working fine.
but when I am trying to add ag-grid in your sample demo project ag-grid is not working at all.

**Comment by hotforfeature** [comment]
There's going to be limited support I can offer. If you can debug and figure out what about Origami is causing ag-grid not to work, I'll gladly fix it.

However, I can't spend a lot of time researching when there's no clear direction on what is causing the Angular component not to work, or if it's even Origami that is causing the problem.

**Comment by nishantgirbar** [comment]
issue is resolved
