### ISSUE TITLE
Compile time errors Demo not working after npm/bower install

### ISSUE THREAD

**Issue by xaffar** [hotforfeature/origami#69]
I downloaded zip, and installed both npm and bower packages.
getting this error in app.module.ts
![image](https://user-images.githubusercontent.com/33129792/32063237-170a244a-ba90-11e7-81d1-44b703e423bc.png)

Folder exists in node modules, not sure what I missed :confused: 
NPM version: 3.10.10
Bower: 1.8.2
typescript: 2.5.3

**Comment by hotforfeature** [comment]
What version of Origami do you have installed?

You should consider upgrading to NPM v5. The demo folder has a package-lock.json which ensures the versions match exactly what was used in the project. There may be some packages that are upgrading to a newer minor version that actually introduces breaking changes.

Typescript in particular is incredibly guilty of breaking semver.

**Comment by russoturisto** [comment]
Same issue here.  Turns out its TypeScript 2.5.3 that breaks it (compiles fine with 2.5.2).

Thanks, :)

**Comment by hotforfeature** [comment]
Don't forget that the Angular CLI [does not officially support typescript 2.5.x](https://github.com/angular/angular-cli/blob/master/package.json#L93) yet. You should be getting console warnings about a typescript mismatch whenever you build or serve.

**Comment by hotforfeature** [comment]
Closing since this is a TS issue. To avoid accidentally updating to a later version of a dependency, use NPM v5+ and the demo project's package-lock.json.
