### ISSUE TITLE
Metadata version mismatch for module node_modules/@codebakery/origami/origami.d.ts

### ISSUE THREAD

**Issue by jayeshagwan1** [hotforfeature/origami#71]
Hi Team,

We are getting error today after doing npm install.
![image](https://user-images.githubusercontent.com/616970/33019245-84a9343a-ce1f-11e7-8d4f-5948dd21c50c.png)

We tried with 1.3.1, 1.3.2 and 1.3.3 versions  but still getting above error.

If we downgrade version to 1.3.0 it works fine.

Due to this issue we are not able to create prod builds.
Need quick help team !!!

**Comment by hotforfeature** [comment]
What version of Angular and CLI are you using?

**Comment by hotforfeature** [comment]
@jayeshagwan1 try version 1.3.4, I think when I built the other ones I was using a later version of the CLI. Been switching between master and my v2 branch without re-installing node modules ;_;

**Comment by jayeshagwan1** [comment]
Thanks @hotforfeature for response. 
We are using NG4 and @angular/cli: 1.2.1. After making version to '^1.3.4' build is working correctly. 
Any breaking changes to be expected in coming days?

**Comment by hotforfeature** [comment]
Glad that fixed it! There won't be any breaking changes or new features in v1.
