### ISSUE TITLE
"<my-coustom-element> is not registered" warning and two way binding doesn't work

### ISSUE THREAD

**Issue by sarathsaleem** [hotforfeature/origami#73]
I am using Angular 5+,

My `index.html` looks like this

```
<link rel="icon" type="image/png" href="favicon.png">
<script src="scripts/webcomponents-lite.js"></script>
<script>
  /* this script must run before Polymer is imported */
  window.Polymer = {
    dom: 'shadow',
    lazyRegister: true,
    useNativeCSSProperties: true
  };
</script>
<link rel="import" href="polymer_loader.html"><!-- all polymer components --> 
<title>MyApp</title>
<div>
  <app-root></app-root>
</div>
```

And I changed main.ts like
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { webcomponentsReady } from '@codebakery/origami';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}
webcomponentsReady().then(() => {
  platformBrowserDynamic().bootstrapModule(AppModule, {
    enableLegacyTemplate: false
  })
    .catch(err => console.log(err));
})
```

But whenever I add `emitChanges` , in logs I can see a warning 
`< my-coustom-element > is not registered`  and other polymer elements that are not registered. 
So the two-way binding doesn't work. But polymer element is rendering and working as expected.

Any clue why this is happening?

**Comment by hotforfeature** [comment]
What is the purpose of this script?
```
<script>
  /* this script must run before Polymer is imported */
  window.Polymer = {
    dom: 'shadow',
    lazyRegister: true,
    useNativeCSSProperties: true
  };
</script>
```
For one, this looks like Polymer 1 global settings. If you're using Polymer 1, know that Origami is only officially compatible with Polymer 2.

My guess would be that `lazyRegister: true` is deferring the registration of custom elements asynchronously and that they are registered after the page (and Angular) loads. So at the time that Angular loads your custom elements, they are not defined and Origami issues the warning.

You shouldn't need any of those global Polymer settings. Polymer 1 defaults to using shadow dom and native CSS properties. Polymer 2 uses webcomponentsjs v1, which again uses shadow dom and native CSS properties by default, only polyfilling when needed when you using the `webcomponents-loader.js` file.

**Comment by sarathsaleem** [comment]
Thanks. So the problem was with polymer version. Some web components that  I used was in polymer 1.x and hence cause the issue.
