### ISSUE TITLE
PolymerChanges doesn't exist

### ISSUE THREAD

**Issue by ahmadhsalim** [hotforfeature/origami#74]
The `import { PolymerChanges } from '@codebakery/origami';` as described in the read me file doesn't work.
`ng build` gives the following error. 

`error TS2305: Module '"/var/www/app/node_modules/@codebakery/origami/origami"' has no exported member 'PolymerChanges'.`

**Comment by hotforfeature** [comment]
Thanks for the report! Looks like I missed a line when re-writing the readme. I've now removed that import from the example code.

Both `PolymerChanges` and `emitChanges` were [deprecated and removed in v2](https://github.com/hotforfeature/origami/issues/62), so they definitely shouldn't be showing up in the docs.
