### ISSUE TITLE
Support for embedded media in Polymer elements ?

### ISSUE THREAD

**Issue by PBM42** [hotforfeature/origami#76]
If there is a Polymer component that use an image:
````html
<img src$="[[importPath]]checked.jpg">
````
How will it be handled ?
Is this the best way to do ?
````js
const img = require('./checked.jpg');
````
````html
<img src$="[[img]]">
````

**Comment by hotforfeature** [comment]
polymer-webpack-loader [only handles external stylesheets and `<link>` elements](https://github.com/webpack-contrib/polymer-webpack-loader/blob/master/src/index.js#L70-L125), so I believe the final effect would be that `[[importPath]]checked.jpg` will need to resolve relative (or absolutely) to the server the project is served on.

So for a common Angular CLI project that has an `assets/` folder provided at runtime, you could set `importPath` equal to `assets/` and have `checked.jpg` reside in that folder. It should resolve after being built and served.

**Comment by PBM42** [comment]
Ok, thanks.
It may be cumbersome if it's in a third party Polymer element.
