### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by flex123** [hotforfeature/origami#77]
Hello..  Thanks a lot for this library and I'm able to use polymer components with Angular.  I'm trying to run some unit tests on an angular component that makes use of a polymer component.  When I run "ng test", I got the following error.  Is there some kind of special configurations that need to be done? I referred to the demo app and I don't see any unit test there. Thanks a bunch.

--------------------------------------------------------------------------------------------
23 03 2018 12:05:18.275:INFO [Chrome 64.0.3282 (Windows 7.0.0)]: Connected on s
cket Im0gsWtkzlGzILmmAAAA with id 69637960
Chrome 64.0.3282 (Windows 7.0.0) ERROR
  {
    "message": "Uncaught TypeError: Failed to construct 'HTMLElement': Please u
e the 'new' operator, this DOM object constructor cannot be called as a functio
.\nat http://localhost:9876/_karma_webpack_/main.bundle.js:14013:105\n\nTypeErr
r: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM o
ject constructor cannot be called as a function.\n    at new DomModule (http://
ocalhost:9876/_karma_webpack_/main.bundle.js:14013:105)\n    at Function.regist
r (http://localhost:9876/_karma_webpack_/vendor.bundle.js:91552:16)\n    at Obj
ct../src/bower_components/iron-overlay-behavior/iron-overlay-backdrop.html (htt
://localhost:9876/_karma_webpack_/main.bundle.js:5750:22)\n    at __webpack_req
ire__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Ob
ect../src/bower_components/iron-overlay-behavior/iron-overlay-manager.html (htt
://localhost:9876/_karma_webpack_/main.bundle.js:6679:1)\n    at __webpack_requ
re__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Obj
ct../src/bower_components/iron-overlay-behavior/iron-overlay-behavior.html (htt
://localhost:9876/_karma_webpack_/main.bundle.js:5874:1)\n    at __webpack_requ
re__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Obj
ct../src/bower_components/paper-dialog-behavior/paper-dialog-behavior.html (htt
://localhost:9876/_karma_webpack_/main.bundle.js:9402:1)\n    at __webpack_requ
re__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)",
    "str": "Uncaught TypeError: Failed to construct 'HTMLElement': Please use t
e 'new' operator, this DOM object constructor cannot be called as a function.\n
t http://localhost:9876/_karma_webpack_/main.bundle.js:14013:105\n\nTypeError:
ailed to construct 'HTMLElement': Please use the 'new' operator, this DOM objec
 constructor cannot be called as a function.\n    at new DomModule (http://loca
host:9876/_karma_webpack_/main.bundle.js:14013:105)\n    at Function.register (
ttp://localhost:9876/_karma_webpack_/vendor.bundle.js:91552:16)\n    at Object.
/src/bower_components/iron-overlay-behavior/iron-overlay-backdrop.html (http://
ocalhost:9876/_karma_webpack_/main.bundle.js:5750:22)\n    at __webpack_require
_ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Object
./src/bower_components/iron-overlay-behavior/iron-overlay-manager.html (http://
ocalhost:9876/_karma_webpack_/main.bundle.js:6679:1)\n    at __webpack_require_
 (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Object.
/src/bower_components/iron-overlay-behavior/iron-overlay-behavior.html (http://
ocalhost:9876/_karma_webpack_/main.bundle.js:5874:1)\n    at __webpack_require_
 (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)\n    at Object.
/src/bower_components/paper-dialog-behavior/paper-dialog-behavior.html (http://
ocalhost:9876/_karma_webpack_/main.bundle.js:9402:1)\n    at __webpack_require_
 (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)"
  }

**Comment by hotforfeature** [comment]
Looks like your tests are running compiled to ES5, and you're testing on a browser that supports customElements. You need to include `webcomponentsjs/custom-elements-es5-adapter.js` before your tests are run.

Add the adapter to the `files` array in your karma configuration `karma.conf.js` file before your test files. You should only add it when you start a test on an ES6 browser, don't add it when you're running tests on IE11 or it will spit out a syntax error and fail your tests.

Additionally, be sure to import `webcomponentsjs/webcomponents-lite.min.js` with your other test polyfills if you're testing on browsers that don't support customElements.

**Comment by flex123** [comment]
Thank you very much! That solved the issue.

**Comment by hotforfeature** [comment]
Glad to hear it!
