### ISSUE TITLE
Any way to run this with Angular 6?

### ISSUE THREAD

**Issue by David-Mulder** [hotforfeature/origami#80]
Per title.

**Comment by hotforfeature** [comment]
Not yet, but I'm be working on Angular 6 support :)

**Comment by David-Mulder** [comment]
Angular 6 + Polymer 3 sounds like one nice match :D

**Comment by willy-juisan** [comment]
@hotforfeature when will you planned to add support for angular 6 and polymer 3?

**Comment by hotforfeature** [comment]
This is now available in v2.0.4! Note that this is only Angular 6/Polymer 2 support. Polymer 3 support will be coming in #57
