### ISSUE TITLE
Dynamic/defer importing the AppModule makes the app failed to compile

### ISSUE THREAD

**Issue by dwiyatci** [hotforfeature/origami#86]
I did pretty much as instructed in my `main.ts`:

```ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { webcomponentsReady } from '@codebakery/origami/polyfills';

// import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

webcomponentsReady().then(() => {
  // requires "module: "esnext" in tsconfig.json
  const { AppModule } = import('./app/app.module');
  platformBrowserDynamic().bootstrapModule(AppModule);
});
```

But when I start the app (`yarn prepare:es5 && ng serve`), it throws the following error:
`ERROR in Tried to find bootstrap code, but could not. Specify either statically analyzable bootstrap code or pass in an entryModule to the plugins options.`

Not deferring the import of the AppModule works fine, though.

What could have I missed here? 🤔

**Comment by asyncLiz** [comment]
Dynamic `import()` returns a Promise, so you must wait for that resolved value. Looks like the documentation is incorrect.

```
webcomponentsReady().then(() => {
  // requires "module: "esnext" in tsconfig.json
  return import('./app/app.module');
}).then(({ AppModule }) => {
  platformBrowserDynamic().bootstrapModule(AppModule);
});
```

I'll update the README to reflect that, thanks for catching it!

**Comment by dwiyatci** [comment]
Thanks for the quick response but the same error thrown after I changed it to that construct...

**Comment by asyncLiz** [comment]
Add this to `tsconfig.app.json`:

```
{
  "angularCompilerOptions": {
    "entryModule": "app/app.module#AppModule"
  }
}
```

I apologize, I didn't carefully read your previous error message. Since we're dynamically bootstrapping it, we need to specifically tell Angular where the bootstrapped module is since it can't infer it.

**Comment by dwiyatci** [comment]
Awesome, that just made my day. Thanks loads! 🙇
