### ISSUE TITLE
Update for Angular 7 support

### ISSUE THREAD

**Issue by gchaville** [hotforfeature/origami#88]
I recently update my Angular project to `Angular 7` and I've got this warning when I `npm install`

```shell
npm WARN @codebakery/origami@3.0.2 requires a peer of @angular/core@^5.0.0-rc.0 || ^5.0.0 || ^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
```
It's a just a warning not a big deal! But it'll be great to support `^7.0.0`

**Comment by gchaville** [comment]
Hi @asyncLiz , any news about the update?

**Comment by asyncLiz** [comment]
Hey @gchaville! It's been a bit crazy for me for the past few weeks with a new release at work, so I haven't had a chance to test Angular 7 yet.

It's still on my radar though! Just might take a little time to get to. If you want to do any testing of your own and post the results here or in a PR, that'd be very welcome.

**Comment by asyncLiz** [comment]
Support has been added in 3.1.0!

**Comment by gchaville** [comment]
Thanks a lot 😁 @asyncLiz
